### ISSUE TITLE
Fix:  Home page needs MUI

### ISSUE THREAD

**Issue by ssimmons05** [aaron-org/snapit-hacktoberfest#118]
The Home.jsx file has some html elements that need to be updated to utilize MUI components instead.

https://mui.com/components/typography/#component
https://mui.com/components/box/#main-content

https://github.com/SnapITSolutions/snapit-hacktoberfest/blob/9ab6273a82b798dde1d5e93201164f649502020c/src/pages/Home/Home.jsx#L11-L51

**Comment by fatima-ola** [comment]
@ssimmons05  I will like to work on this issue
