### ISSUE TITLE
Welcome Page (After Countdown)

### ISSUE THREAD

**Issue by lisphelps** [aaron-org/snapit-hacktoberfest#67]
As a user, I wish to see the Welcome Page differently once October begins - the countdown should be replaced.

**Comment by tchestnut85** [comment]
Hi @lisphelps, could you assign this to me?

**Comment by tchestnut85** [comment]
Opened a PR for this fix - #97 
I included a screenshot, but if a test is required too let me know and I'll update my PR. It's getting late and I need to get up early tomorrow 😆

**Comment by tchestnut85** [comment]
Thanks! Ok no problem, I'll get that done later on today.

**Comment by tchestnut85** [comment]
Hey @aaronshivers , I updated my PR for this with some tests to check for the changed heading and the link I added. I updated some of the tests to skip based on whether it's currently hacktoberfest or not so they shouldn't fail 🙏 .

Can you run the tests again and review when you get a chance? Thank you!
