### ISSUE TITLE
Add link of this repository on the website

### ISSUE THREAD

**Issue by Maaz-Code** [aaron-org/snapit-hacktoberfest#91]
#### A button can be created which will link to this GitHub repository for visitors who want to contribute to the website.

**Comment by aaronshivers** [comment]
@Maaz-Code That's a great idea. We could even add a projects page in the future. Do you want to add a link on the information page for now, then we can add a projects page issue later?

**Comment by Maaz-Code** [comment]
Yes, I can add the repo link on the information page for now and the projects page can be added later.

**Comment by Maaz-Code** [comment]
I am not able to run the project on local machine as the nvm is not installing the correct node version

**Comment by aaronshivers** [comment]
@Maaz-Code Were you able to get the issue resolved?

**Comment by ssimmons05** [comment]
I'm hoping this might be helpful to you.

https://github.com/coreybutler/nvm-windows/releases

**Comment by ssimmons05** [comment]
I think you can just extract the link itself and place it below where the mapping function ends in the information.jsx file.
  
  And you can use this to see how MUI handles links:  
  https://mui.com/components/links/#main-content
